# Generated by Django 5.2 on 2025-04-04 09:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('inv_amt', models.PositiveIntegerField()),
                ('exp_returns', models.FloatField()),
                ('risk_tolerance', models.CharField(choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High')], max_length=10)),
                ('inv_duration', models.CharField(max_length=32)),
                ('pref_invest_type', models.CharField(max_length=32)),
                ('emp_status', models.CharField(max_length=32)),
                ('source', models.CharField(max_length=32)),
                ('pan_num', models.CharField(max_length=10)),
                ('aadhar_num', models.CharField(max_length=12)),
                ('gov_id', models.ImageField(upload_to='gov_ids/')),
                ('on_boarding_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
